#!/bin/bash
# Count the number of directories and sub-directories
count=$(find . -mindepth 1 -type d -not -path '*/\.*' | wc -l)
# Print the result
echo "Number of directories and sub-directories: $count"

